### ISSUE TITLE
IPv6 branch

### ISSUE THREAD

**Issue by ghost** [ApolloRIP/Ocelot#15]
The only change on ipv6 branch is for Ocelot? Gazelle is not changed?

**Comment by itismadness** [comment]
That is correct, Gazelle itself doesn't need changes to support IPv6 (you can already connect to the site using IPv6 just fine).

Saying that, once proper IPv6 support has landed, we may do like empornium and add in a user setting that turns on/off support for getting IPv6 peers returned to you regardless of your IPv6 capabilities, but I'm undecided on that.
