### ISSUE TITLE
Looking for Ocelot customization based on my custom XBT.

### ISSUE THREAD

**Issue by XFDev-v2** [ApolloRIP/Ocelot#16]
Hello
i am looking for someone to customize Ocelot as per my XBT as my custom XBT is not properly codded by my coder as it keep crashing any moment and make tracker much unstable.
https://github.com/XFDev-v2/XenForo-1.5.x-Torrent-Tracker/tree/master/xbt
This is my custom XBT codded for and xenforo 1.5.x based forum software.
if anyone willing to help and do, please contact me or share me your contact details.
Thanks

**Comment by itismadness** [comment]
Closing this as this isn't an issue with ocelot itself.
