### ISSUE TITLE
About error message "Peer field is of invalid of length" on Utorrent

### ISSUE THREAD

**Issue by riverstore** [ApolloRIP/Ocelot#24]
Hi, Does anyone meet problem that Utorrent 3.5.5 (and maybe from 3.3.x) with message "Peer field is of invalid of length"?

This not happen on qBittorrent.

Anyone know the issue please help me.

Thanks a lot.

Regard.

**Comment by LokiThor2021** [comment]
Yes, we have the same issue.

**Comment by sheepish-ops** [comment]
master with ipv6 code is quite buggy. If you run in production use the tagged 2.0.0 version which is ipv4-only.

**Comment by sheepish-ops** [comment]
IPv6 code is removed from master now.
