### ISSUE TITLE
ocelot.conf

### ISSUE THREAD

**Issue by DuR4c3ll** [ApolloRIP/Ocelot#4]
`-c <path/to/ocelot.conf>`
Where is the ocelot.conf? 
I cannot see it anywhere and all I can see is the config.cpp

`Using default config because './ocelot.conf' couldn't be opened
Start Ocelot with -c <path> to specify config file if necessary`

ty

**Comment by itismadness** [comment]
Copy the [ocelot.conf.dist](https://github.com/ApolloRIP/Ocelot/blob/master/ocelot.conf.dist) to somewhere naming it ocelot.conf and setting your details in it.

**Comment by DuR4c3ll** [comment]
Thanks!
