### ISSUE TITLE
Move to cmake over autotools

### ISSUE THREAD

**Issue by itismadness** [ApolloRIP/Ocelot#8]
It'd be good to drop autotools in favor of cmake which is a bit nicer in portability, design, and usage.

**Comment by waruqi** [comment]
Also consider using other build systems, such as: https://github.com/tboox/xmake 😄

**Comment by itismadness** [comment]
Done in a7d8e5744f1399507a6e6dfc07a0872f409a8e96.

Perhaps some future developer will have an interest in adopting xmake or meson, but I'm just satisfied moving off autotools for now.
